# 기본 이미지 설정
FROM nvidia/cuda:11.4.3-cudnn8-devel-ubuntu18.04

# 환경변수 설정
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Seoul
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

# 필요한 패키지 설치
RUN apt-get update && apt-get install -y \
    libedit-dev \
    libffi-dev \
    wget \
    cmake \
    libopencv-dev \
    unzip

# Python 3.8 설치
RUN apt-get install -y python3.8 python3.8-dev python3.8-distutils

# Pip 설치
RUN wget https://bootstrap.pypa.io/get-pip.py && \
    python3.8 get-pip.py

# Ninja 빌드 시스템 설치
RUN wget https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip && \
    unzip ninja-linux.zip -d /usr/local/bin/ && \
    update-alternatives --install /usr/bin/ninja ninja /usr/local/bin/ninja 1 --force

RUN pip install lmdb
# Python 라이브러리 설치
RUN pip install numpy==1.21.0 \
                scipy==1.7.0 \
                matplotlib==3.4.2 \
                opencv-python==4.5.3.56 \
                tqdm==4.61.2 \
                wget==3.2 \
                dlib==19.21.0 \
                ninja==1.10.2 \
                scikit-image==0.18.1 \
                pillow==8.3.1 \
                certifi==2021.10.8 \
                faiss-cpu==1.7.1

# 도커 컨테이너 기본 명령 설정
CMD ["bash"]
